### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by C47D** [IRNAS/ppk2-api-python#2]
Hi,

I would like to know if you have a roadmap for features to be implemented, I'm about to get access to one PPK2 and I'm looking forward to use your library.

**Comment by SloMusti** [comment]
At the moment, there is no particular roadmap in place as this is an internal project here at IRNAS, where we add improvements as we expand the use of ppk2. Everyone is welcome to open issues and label them as `enhancement` for required features which will be handled best-effort or create pull-requests which will get reviewed promptly.

**Comment by C47D** [comment]
Hi,

Thanks for the reply, I will do so if I find any issue or need help with a feature.
