### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by bearsh** [IRNAS/ppk2-api-python#20]
Hi, I currently write a golang library to access ppk2 devices. My code is heavily based on this library.

Now I think about the license to use for my library. As it is based on your work, I most probably have to use the same license. But thinking more about this, I also wonder if it was Ok after all to publish this library under GPL v2 as this library itself if AFAIK partly based on Nordic's work which itself use another license...

I have no problem with the GPL v2 but I would prefer to use a less restrictive license, at least LPGL.

What do you think?

**Comment by SloMusti** [comment]
Please use the same license as re-licensing now would be an issue.
