### ISSUE TITLE
Serial read/write never times out if PPK2 goes in bad state

### ISSUE THREAD

**Issue by lorjala** [IRNAS/ppk2-api-python#23]
After opening serial connection and if PPK2 goes in bad state then following serial reads or writes never timeout.

Exclusive flag should be passed when creating serial connection:
https://github.com/IRNAS/ppk2-api-python/blob/f05ca671cf73de76c68eefe499acf745c1e81908/src/ppk2_api/ppk2_api.py#L52

Also allowing to pass read/write timeout options to pyserial through the constructor would be nice.

**Comment by NejcKle** [comment]
@lorjala please test the fix I have made in 7bb1d5b.

**Comment by NejcKle** [comment]
@juhhov Great idea actually! I have added this in 3450e73.

**Comment by lorjala** [comment]
Thanks! This looks good now.

Please make a new release with these changes when you can.

**Comment by NejcKle** [comment]
@lorjala 
Release 0.9.1 has been published here and to https://pypi.org/project/ppk2-api/. 
I am closing this issue.
