### ISSUE TITLE
Implement Triggering Event?

### ISSUE THREAD

**Issue by Jinyaox** [IRNAS/ppk2-api-python#27]
Referring to #6 
I wonder if you plan to implement trigger detection (digital) soon in future. I am writing a paper for power analysis and it would be awesome if that feature can be implemented!

**Comment by NejcKle** [comment]
Hi @Jinyaox,

[release 0.9.2.](https://github.com/IRNAS/ppk2-api-python/releases/tag/v0.9.2) implements digital channels. You can implement trigger detection using the provided API.
