### ISSUE TITLE
Documentation for ppk2

### ISSUE THREAD

**Issue by aquil-rodrigues** [IRNAS/ppk2-api-python#28]
## Description

Which document was referred for developing the package

I would like to contribute for this project so it would be helpful

**Comment by NejcKle** [comment]
@aquil-rodrigues this package has been developed by referring to the official [pc-nrfconnect-ppk](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk) application and the [ppk_api](https://github.com/wlgrd/ppk_api).

**Comment by cranialhum** [comment]
Hi @NejcKle.
I've been checking out your code for converting the raw measurement data to current draw measurements, and was wondering if you could point to, or explain, the derivation of the get_adc_result function - particularly the below lines.
Thanks in advance!

```
        result_without_gain = (adc_value - self.modifiers["O"][current_range]) * (
            self.adc_mult / self.modifiers["R"][current_range])
        adc = self.modifiers["UG"][current_range] * (result_without_gain * (self.modifiers["GS"][current_range] * result_without_gain + self.modifiers["GI"][current_range]) + (
            self.modifiers["S"][current_range] * (self.current_vdd / 1000) + self.modifiers["I"][current_range]))
```

**Comment by NejcKle** [comment]
Hello @cranialhum, the API is translated from Typescript into Python and is based on the official [pc-nrfconnect-ppk](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk)]https://github.com/NordicSemiconductor/pc-nrfconnect-ppk app. The lines you are referring to can be found [here](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/blob/c1f38f2a291851c4331d32f67c14ed14c789283b/src/device/serialDevice.ts#L126).
