### ISSUE TITLE
Sampling Rate

### ISSUE THREAD

**Issue by Jinyaox** [IRNAS/ppk2-api-python#29]
Hello, is there a way to change sampling rate for the device? If not, what is the default sampling rate for this sampling?

**Comment by wlgrd** [comment]
No. The sampling/reporting rate of the PPK2 is 100k samples/second.

**Comment by Siddarth-Manja** [comment]
Is there any script to average the obtained value to 10k samples/second the way it is done in the nRF connect desktop application?

**Comment by wlgrd** [comment]
Not right now.
