### ISSUE TITLE
ModuleNotFoundError: No module named 'ppk2_api'

### ISSUE THREAD

**Issue by krupis** [IRNAS/ppk2-api-python#38]
Hello. I have been refered to this repository from the nrf devzone. Perhaps this is exactly what I am looking for (I need to be able to measure the current consumption using Python script instead of GUI).

Could you please help me understand how to get it working for the first time? I have just downloaded the repository and launched example.py script. After trying to run it, I am getting the following error:
```
Traceback (most recent call last):
  File "C:\Users\petrikas.lu\Downloads\ppk2-api-python-master\ppk2-api-python-master\example.py", line 10, in <module>
    from ppk2_api.ppk2_api import PPK2_API
ModuleNotFoundError: No module named 'ppk2_api'
```
It does not seem to find ppk2_api even though it is located at:

```
Downloads\ppk2-api-python-master\ppk2-api-python-master\src\ppk2_api
```

**Comment by NejcKle** [comment]
Hi @krupis, once you have cloned the repo you will have to install the python module by running `pip3 install .` from the root directory of the repo.

**Comment by krupis** [comment]
@NejcKle Thanks for a quick reply. I was not aware of this method to install required python modules. Can you explain a little bit about how it works? :o

**Comment by krupis** [comment]
@NejcKle 

I am aware of installing packages using ```pip install```. I was just not aware that you can do ```pip install .``` to install all required modules .

So if I move ```ppk2_api``` from the ```C:\Users\petrikas.lu\Downloads\ppk2-api-python-master\ppk2-api-python-master\src\ppk2_api``` to the root directory of the project ```C:\Users\petrikas.lu\Downloads\ppk2-api-python-master\ppk2-api-python-master```, then I can use this ppk2_api.py without installing the package?

**Comment by wlgrd** [comment]
Closing stale issue.
