### ISSUE TITLE
Question / Issue on opcodes in PPK2_Command() 

### ISSUE THREAD

**Issue by DargarWhiteFang** [IRNAS/ppk2-api-python#44]
Hi

I noticed OpCode 0x11 is duplicated, listed as both "TRIGGER_EXT_TOGGLE" and "SET_POWER_MODE" -> is that double-assignment correct?

I also have some general questions on the API:
1. Are there any documents available to explain the op-codes, arguments (if any), and expected replies?
2. Is the opcode list in ppk2_api.py complete?

**Comment by NejcKle** [comment]
Hello @DargarWhiteFang 

The double assignment is correct and the list is complete. The `TRIGGER_STOP` command seems to be deprecated, but is still included in the list.

AFAIK there is no document to describe the OP codes and the return values.
We used the official [pc-nrfconnect-ppk](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk) app and the [PPK1 Python API](https://github.com/wlgrd/ppk_api) from @wlgrd to create the PPK2 Python API.
