### ISSUE TITLE
Sampling digital IOs on the Logic port

### ISSUE THREAD

**Issue by rdagher** [IRNAS/ppk2-api-python#48]
Hello. 

Is there a way to sample the digital IOs (D0-D7) on the logical port?

Cheers !

Roudy

**Comment by tyeth** [comment]
Looks like it's converter function is here: https://github.com/IRNAS/ppk2-api-python/blob/8c9459d92f3224f68b41fcfe05b9bd087bbf7e15/src/ppk2_api/ppk2_api.py#L339-L344

And the example uses it here:
https://github.com/IRNAS/ppk2-api-python/blob/8c9459d92f3224f68b41fcfe05b9bd087bbf7e15/example.py#L36-L45
