### ISSUE TITLE
How to read digital outputs?

### ISSUE THREAD

**Issue by luizmanke** [IRNAS/ppk2-api-python#6]
PPK2 is capable of reading digital outputs.
With the Power Profiler (nRF Connect) there's an option to select these ports in the side bar.
How can I do that with your python module?

Here's an image of how I set up the digital outputs in the Power Profiler:

![image](https://user-images.githubusercontent.com/37818079/111361036-3349da00-866c-11eb-8d2e-2c74c654d65a.png)

**Comment by NejcKle** [comment]
Hi @luizmanke, 

as of right now this feature has not been implemented yet. We plan to do so in the future.

**Comment by 0ette** [comment]
Hey @NejcKle,

Do you have any idea when that would be implemented? I am loving the API and the digital channels would take it to another level :)

**Comment by SloMusti** [comment]
@0ette there are no specific timelines available for this as this library is primarily upgraded as we require extra features internally irnas.eu and work on it is best-effort. Should you require this immediately for an industrial project, please reach out and we can support you immediately.

**Comment by kromancer** [comment]
For the shake of completeness I dropped this question in devzone:
https://devzone.nordicsemi.com/f/nordic-q-a/81824/python-api-for-digital-tracing-with-the-ppk2

If one would go about adding this functionality,
would he have to see how it is done here:
https://github.com/NordicSemiconductor/pc-nrfconnect-ppk
?

**Comment by wlgrd** [comment]
Yes @kromancer , and this would also help
```
                                                      |-- Battery present, bit 17
            |-- Logic state, 8 bits (24-31)           |   |-- Range, 3 bits (14-16)
            |                     | count (18-23)     |   |     |
            |      Logic  (8bits) |                   B   | R   |    Analog samples, 14 bits (0-13)       |
    Bit     31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 09 08 07 06 05 04 03 02 01 00
```

**Comment by karthik-gunturi** [comment]
Is there any progress on this thread?

**Comment by stevehuj** [comment]
Hello, after all this time, is there any progress in controlling the digital channels?
I've noticed someone has been working hard on the project lately, so an expansion with this feature would be very awesome.
